### ISSUE TITLE
Use of non-standard function causes install to fail

### ISSUE THREAD

**Issue by another4til7** [dev47apps/droidcam-linux-client#285]
**Describe the bug**
Trying to (re)install droidcam fails with errors

wget -O droidcam_latest.zip https://files.dev47apps.net/linux/droidcam_2.0.0.zip
...
sudo wget -O droidcam_latest.zip https://files.dev47apps.net/linux/droidcam_2.0.0.zip
....
cd droidcam && sudo ./install-client
...
sudo apt install libappindicator3-1
...
sudo apt install linux-headers-`uname -r` gcc make
sudo ./install-video
Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entering directory '/tmp/droidcam/v4l2loopback'
make -C /lib/modules/6.8.0-40-generic/build M=/tmp/droidcam/v4l2loopback modules
make[1]: Entering directory '/usr/src/linux-headers-6.8.0-40-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /tmp/droidcam/v4l2loopback/v4l2loopback-dc.o
/tmp/droidcam/v4l2loopback/v4l2loopback-dc.c: In function ‘vidioc_querycap’:
/tmp/droidcam/v4l2loopback/v4l2loopback-dc.c:622:3: error: implicit declaration of function ‘strlcpy’; did you mean ‘strscpy’? [-Werror=implicit-function-declaration]
  622 |   strlcpy(cap->driver, "Droidcam", sizeof(cap->driver));
      |   ^~~~~~~
      |   strscpy
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /tmp/droidcam/v4l2loopback/v4l2loopback-dc.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-40-generic/Makefile:1926: /tmp/droidcam/v4l2loopback] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-40-generic'
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/tmp/droidcam/v4l2loopback'

**Expected behavior**
(Re)installing droidcam produces a working install

**Additional context**
Ubuntu 22.04.1 LTS

A similar bug (issue 271) was filed and the response was to apply a kernel patch. Suggestions to add this patch to the installation were ignored. 

But, that response ignored that the problem is because 1 the strlcpy function is a non-standard function ((https://github.com/RsyncProject/rsync/issues/324) and that Kernel Compilation is explicilty discouraged by the average user. 

The official Ubuntu article on Kernel/Compile notes that one of the "Reasons for NOT compiling a custom kernel" is that "you have no idea what you are doing, and if you break something, you'll need help fixing it." I suspect this describes the bulk of us using Droidcam.

Rather than offering a kernel patch, perhaps the easier solution is to include some if statement that detects linux and (if so) uses a standard function to do the same thing. Alternatively, tell us what to change the source code to before we run install-video.

**Comment by aramg** [comment]
Hello,

* If you follow #271 you will see that this was patched in droidcam v2.1.3. You are downloading v2.0.0.
* You can just install `v4l2loopback-dkms` and avoid the `./install-video` script as per instructions / readme. 
* No other Ubuntu 22.04.1 LTS compilation errors have been reported, I dont believe this is an active bug

**Comment by another4til7** [comment]
Thanks @aramg. That did sort it out. 

FWIW, something was causing the kernel module to vaporize regularly (usually discovered as I was trying to go into a zoom meeting) so I acted like a good sysadmin and turned setup into a tiny shell script. I just modified that script to automatically determine the latest release by looking on github. Hopefully that prevents a future out-of-date error.
