### ISSUE TITLE
Droidcam obs paid version auto zooms in to face

### ISSUE THREAD

**Issue by kingpincho** [dev47apps/droidcam-linux-client#287]
My issue is whenever I use one of my rear cameras on a galaxy s23 ultra it always after some time (30sec to 1-2min) I get an automatic zoom level up to my face and I can't find an option to stop it. For example if I use my front camera I don't have that issue a d everything works the way it's supposed to (without automatic zoom to my face). 
It does it over Wi-Fi and USB connection to OBS. 
I tried different resolutions 720p,1080p,4k - same story
Even installed the remote control add-on for obs and it does detect the zoom level applied Automatically, so every time I counter it back to 1x or 0.6x after some time it goes again very close to my face with around 5x-6x zoom .

**Comment by aramg** [comment]
Please contact support@dev47apps.com for help on this.
